
package com.github.adminfaces.starter.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ManifesteWebService", targetNamespace = "http://ws.douane.papn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ManifesteWebService {


    /**
     * 
     * @param debut
     * @param fin
     * @param trafic
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getManifesteXML", targetNamespace = "http://ws.douane.papn/", className = "com.github.adminfaces.starter.ws.GetManifesteXML")
    @ResponseWrapper(localName = "getManifesteXMLResponse", targetNamespace = "http://ws.douane.papn/", className = "com.github.adminfaces.starter.ws.GetManifesteXMLResponse")
    @Action(input = "http://ws.douane.papn/ManifesteWebService/getManifesteXMLRequest", output = "http://ws.douane.papn/ManifesteWebService/getManifesteXMLResponse")
    public List<Object> getManifesteXML(
        @WebParam(name = "debut", targetNamespace = "")
        String debut,
        @WebParam(name = "fin", targetNamespace = "")
        String fin,
        @WebParam(name = "trafic", targetNamespace = "")
        String trafic);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "retrieveManifesteFromDouane", targetNamespace = "http://ws.douane.papn/", className = "com.github.adminfaces.starter.ws.RetrieveManifesteFromDouane")
    @ResponseWrapper(localName = "retrieveManifesteFromDouaneResponse", targetNamespace = "http://ws.douane.papn/", className = "com.github.adminfaces.starter.ws.RetrieveManifesteFromDouaneResponse")
    @Action(input = "http://ws.douane.papn/ManifesteWebService/retrieveManifesteFromDouaneRequest", output = "http://ws.douane.papn/ManifesteWebService/retrieveManifesteFromDouaneResponse")
    public void retrieveManifesteFromDouane();

    /**
     * 
     * @param numVoy
     * @param dateDepart
     * @param numEnreg
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "genererManifeste", targetNamespace = "http://ws.douane.papn/", className = "com.github.adminfaces.starter.ws.GenererManifeste")
    @ResponseWrapper(localName = "genererManifesteResponse", targetNamespace = "http://ws.douane.papn/", className = "com.github.adminfaces.starter.ws.GenererManifesteResponse")
    @Action(input = "http://ws.douane.papn/ManifesteWebService/genererManifesteRequest", output = "http://ws.douane.papn/ManifesteWebService/genererManifesteResponse")
    public String genererManifeste(
        @WebParam(name = "numEnreg", targetNamespace = "")
        String numEnreg,
        @WebParam(name = "numVoy", targetNamespace = "")
        String numVoy,
        @WebParam(name = "dateDepart", targetNamespace = "")
        String dateDepart);

    /**
     * 
     * @param debut
     * @param fin
     * @param trafic
     * @return
     *     returns java.util.List<com.github.adminfaces.starter.ws.RefManResult>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findManifeste", targetNamespace = "http://ws.douane.papn/", className = "com.github.adminfaces.starter.ws.FindManifeste")
    @ResponseWrapper(localName = "findManifesteResponse", targetNamespace = "http://ws.douane.papn/", className = "com.github.adminfaces.starter.ws.FindManifesteResponse")
    @Action(input = "http://ws.douane.papn/ManifesteWebService/findManifesteRequest", output = "http://ws.douane.papn/ManifesteWebService/findManifesteResponse")
    public List<RefManResult> findManifeste(
        @WebParam(name = "debut", targetNamespace = "")
        String debut,
        @WebParam(name = "fin", targetNamespace = "")
        String fin,
        @WebParam(name = "trafic", targetNamespace = "")
        String trafic);

}
