
package com.github.adminfaces.starter.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ManifesteWebService", targetNamespace = "http://ws.douane.papn/", wsdlLocation = "http://10.0.55.210:8080/ManifesteWebService/ManifesteWebService?wsdl")
public class ManifesteWebService_Service
    extends Service
{

    private final static URL MANIFESTEWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException MANIFESTEWEBSERVICE_EXCEPTION;
    private final static QName MANIFESTEWEBSERVICE_QNAME = new QName("http://ws.douane.papn/", "ManifesteWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.0.55.210:8080/ManifesteWebService/ManifesteWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MANIFESTEWEBSERVICE_WSDL_LOCATION = url;
        MANIFESTEWEBSERVICE_EXCEPTION = e;
    }

    public ManifesteWebService_Service() {
        super(__getWsdlLocation(), MANIFESTEWEBSERVICE_QNAME);
    }

    public ManifesteWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), MANIFESTEWEBSERVICE_QNAME, features);
    }

    public ManifesteWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, MANIFESTEWEBSERVICE_QNAME);
    }

    public ManifesteWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MANIFESTEWEBSERVICE_QNAME, features);
    }

    public ManifesteWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ManifesteWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ManifesteWebService
     */
    @WebEndpoint(name = "ManifesteWebServicePort")
    public ManifesteWebService getManifesteWebServicePort() {
        return super.getPort(new QName("http://ws.douane.papn/", "ManifesteWebServicePort"), ManifesteWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ManifesteWebService
     */
    @WebEndpoint(name = "ManifesteWebServicePort")
    public ManifesteWebService getManifesteWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.douane.papn/", "ManifesteWebServicePort"), ManifesteWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MANIFESTEWEBSERVICE_EXCEPTION!= null) {
            throw MANIFESTEWEBSERVICE_EXCEPTION;
        }
        return MANIFESTEWEBSERVICE_WSDL_LOCATION;
    }

}
