
package com.github.adminfaces.starter.util;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AWPAPNWebService", targetNamespace = "http://impl/", wsdlLocation = "http://192.168.115.125:8080/SydoniaPapnWS/AWPAPNWebService?wsdl")
public class AWPAPNWebService_Service
    extends Service
{

    private final static URL AWPAPNWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException AWPAPNWEBSERVICE_EXCEPTION;
    private final static QName AWPAPNWEBSERVICE_QNAME = new QName("http://impl/", "AWPAPNWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.115.125:8080/SydoniaPapnWS/AWPAPNWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AWPAPNWEBSERVICE_WSDL_LOCATION = url;
        AWPAPNWEBSERVICE_EXCEPTION = e;
    }

    public AWPAPNWebService_Service() {
        super(__getWsdlLocation(), AWPAPNWEBSERVICE_QNAME);
    }

    public AWPAPNWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), AWPAPNWEBSERVICE_QNAME, features);
    }

    public AWPAPNWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, AWPAPNWEBSERVICE_QNAME);
    }

    public AWPAPNWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AWPAPNWEBSERVICE_QNAME, features);
    }

    public AWPAPNWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AWPAPNWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AWPAPNWebService
     */
    @WebEndpoint(name = "AWPAPNWebServicePort")
    public AWPAPNWebService getAWPAPNWebServicePort() {
        return super.getPort(new QName("http://impl/", "AWPAPNWebServicePort"), AWPAPNWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AWPAPNWebService
     */
    @WebEndpoint(name = "AWPAPNWebServicePort")
    public AWPAPNWebService getAWPAPNWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl/", "AWPAPNWebServicePort"), AWPAPNWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AWPAPNWEBSERVICE_EXCEPTION!= null) {
            throw AWPAPNWEBSERVICE_EXCEPTION;
        }
        return AWPAPNWEBSERVICE_WSDL_LOCATION;
    }

}
